### ISSUE TITLE
login page needs to be responsive for different device widths

### ISSUE THREAD

**Issue by ppelayo1** [codeforsanjose/gov-agenda-notifier#223]
Currently the login page does not resize as the width shrinks. The login page needs to be responsive to the size of the user's screen.

**Comment by Nerfi** [comment]
Hey there!  is this still open? I'd like to give you a hand !

**Comment by jerrycyip** [comment]
working on it - is there an agreed breakpoint where we switch over to responsive?  I see in some other stylesheets we have media queries at width 812 px, so I can use that if that's what's agreed on.  Otherwise, just let me know if (i)we have a different defined breakpoint and (ii) whether there is just one breakpoint or multiple breakpoints for different devices (e.g. tablet, phone).  Thanks

**Comment by ppelayo1** [comment]
I am not sure on that. Might be good to shout that out on the slack. Hattie Chau made the mock-up design, could perhaps shout out to her in your slack post to see what she thinks.

**Comment by jerrycyip** [comment]
good suggestion.  I'll try reaching out on Slack.  thanks!

**Comment by jerrycyip** [comment]
Reference images for Hattie / design team to consider:
Question: 
1) Should I use the same breakpoint of 812 pixels for login mobile view or a different one?  (if a different one, what is that breakpoint?)
2) Or otherwise should I use multiple breakpoints (one for phone, one for tablet, one for larger devices like laptops), and if so, then can I get mockups and suggested breakpoints?

 (Personally, I'm leaning towards 'yes' to question 1 and no to question 2 - but hoping to get Hattie/design team's input)
**mobile view of login on phone:** 
(ignore lack of logo and 'create an account' section on top and bottom - those haven't been implemented yet):
![phone_login](https://user-images.githubusercontent.com/54079796/122665174-9317bb80-d15a-11eb-9edb-4eb6ff514190.png)
**Tablet view of login on phone (anything below 812 pix - regular ipad = 768px)**
![tablet_login](https://user-images.githubusercontent.com/54079796/122665207-c22e2d00-d15a-11eb-82a0-c6636e19c3b6.png)
This follows same responsive breakpoint (of 812 pixels) as currently used elsewhere with app such as follows:
**Tablet view of meeting list (ignore duplicate meetings - it's fake dummy data):**
![tablet_mtg_list](https://user-images.githubusercontent.com/54079796/122665242-f1449e80-d15a-11eb-9242-a6715ab2a86b.png)
which is same as the phone view:
**Phone view of meeting list:**
![phone_mtg_list](https://user-images.githubusercontent.com/54079796/122665246-fdc8f700-d15a-11eb-8f4f-c530cb64a4fc.png)
