### ISSUE TITLE
Hide any meeting that occurred in the past by default

### ISSUE THREAD

**Issue by feliciafalafelc** [codeforsanjose/gov-agenda-notifier#233]

**Comment by jerrycyip** [comment]
To my knowledge this is how the application works today already.  Specifically, past meetings are hidden by default and the user must select "Show past meetings" box in order to see past meetings.   
If folks agree, let's close this issue.  (btw, do you have an environment set-up to see how the application functions currently?)

**Comment by jerrycyip** [comment]
To my knowledge this is how the application works today already.  Specifically, past meetings are hidden by default and the user must select "Show past meetings" box in order to see past meetings.   
If folks agree, let's close this issue.  (btw, do you have an environment set-up to see how the application functions currently?)
